name: "pull-request"

on:
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: ubuntu-latest
            container: archlinux:latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container || null }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check
      - run: nix develop .#ci

  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: gh pr merge --rebase --auto
    env:
      GH_TOKEN: ${{ secrets.GH_REPO_PAT }}
